# Generated by Django 5.2.3 on 2025-06-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("payment", "Payment"), ("charge", "Charge")],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
